burro:
  heartbeat: 10
  throttler: true
  rules:
    - delay: 0
      rule:
      - src_rse: XRD1
        dst_rse: XRD2
        size_GB: 1000
        n_transfers: 10
        priority: 2
      - src_rse: XRD2
        dst_rse: XRD3
        size_GB: 200
        n_transfers: 20
        priority: 1
    - delay: 15
      rule:
      - src_rse: XRD1
        dst_rse: XRD2
        size_GB: 500
        n_transfers: 5
        priority: 2
dmm:
  host: localhost
  port: 5000
  authkey: /Users/jguiang/Projects/rucio-sense-dmm/dummykey
nonsense:
  host: 127.0.0.1
  port: 5000
  profile_uuid: ddd1dec0-83ab-4d08-bca6-9a83334cd6db
  sites:
    - name: T2_US_UCSD
      full_uri: urn:ogf:t2.ucsd.edu:nrp-dev:T2_US_UCSD
      root_uri: urn:ogf:t2.ucsd.edu:nrp-dev
      port_capacity: 1000000
      ipv6_subnet_pool: "blah"
    - name: T2_US_Caltech_Test
      full_uri: urn:ogf:network:ultralight.org:2013:T2_US_Caltech_Test
      root_uri: urn:ogf:network:ultralight.org:2013
      port_capacity: 1000000
      ipv6_subnet_pool: "2605:d9c0:2:fff1::/64,2605:d9c0:2:fff2::/64,2605:d9c0:2:fff3::/64"
    - name: T2_US_Caltech_Test
      full_uri: urn:ogf:network:ultralight1.org:2013:T2_US_Caltech_Test1
      root_uri: urn:ogf:network:ultralight1.org:2013
      port_capacity: 1000000
      ipv6_subnet_pool: "2605:d9c0:2:fff4::/64,2605:d9c0:2:fff5::/64,2605:d9c0:2:fff6::/64"
    - name: k8s-igrok-01
      full_uri: urn:ogf:network:calit2.optiputer.net:2020:prism-core:k8s-igrok-01
      root_uri: urn:ogf:network:calit2.optiputer.net
      port_capacity: 1000000
      ipv6_subnet_pool: "blah"
    - name: k8s-igrok-02
      full_uri: urn:ogf:network:calit2.optiputer.net:2020:prism-core:k8s-igrok-02
      root_uri: urn:ogf:network:calit2.optiputer.net
      port_capacity: 1000000
      ipv6_subnet_pool: "blah"
psnet:
  time_dilation: 10.0
