burro:
  heartbeat: 10
  throttler: true
  rules:
    - delay: 0
      rule:
      - src_rse: XRD1
        dst_rse: XRD2
        size_GB: 1000
        n_transfers: 10
        priority: 2
      - src_rse: XRD2
        dst_rse: XRD3
        size_GB: 200
        n_transfers: 20
        priority: 1
    - delay: 15
      rule:
      - src_rse: XRD1
        dst_rse: XRD2
        size_GB: 500
        n_transfers: 5
        priority: 2
dmm:
  host: localhost
  port: 5000
  authkey: /Users/jguiang/Projects/rucio-sense-dmm/dummykey
